Added setBrakeMode for chassis
LemLib/LemLib pull request #119
Opened 2023-12-14 07:18 UTC by SecretAgent-YT

#### Summary
In EZ-Template, there's a feature to switch all the drive motor's brake modes. This is used for switching from hold for autonomous to coast in user control.

#### Motivation
This saves 1 line.

#### Test Plan
Tested on robot, switch occurred perfectly. RC1

#### Additional Notes
N/A

2023-12-14 19:46 UTC, Rocky14683 commented
that function shouldn't be taking mutex

2023-12-17 03:32 UTC, SecretAgent-YT commented
> that function shouldn't be taking mutex

Fixed in https://github.com/LemLib/LemLib/pull/119/commits/6e748f119d4869836aadcb22b3ab4914c6a4b6da

2024-01-06 23:56 UTC, SizzinSeal requested changes
Just fix the location of this comment

2024-01-06 23:56 UTC, SizzinSeal commented on include/lemlib/chassis/chassis.hpp
> +         */
```suggestion
         /**
         * @brief Sets the brake mode of the drivetrain motors
         *
         * @param mode Mode to set the drivetrain motors to
         */
        void setBrakeMode(pros::motor_brake_mode_e mode);
```

2024-01-07 00:16 UTC, SizzinSeal requested changes

2024-01-07 00:16 UTC, SizzinSeal commented on include/lemlib/chassis/chassis.hpp
> +         /**
```suggestion
        /**
```

2024-01-07 00:19 UTC, merged