turnToHeading()
LemLib/LemLib pull request #127
Opened 2024-01-04 00:07 UTC by Miniongolf

#### Summary
Implements turn to heading function, renamed old function to `turnToPoint()`.

#### Motivation
Turning to a heading instead of a point is also useful.

#### Test Plan
Plan: run on a robot the same way turnToPoint and other motions would be tested.

#### Additional Notes
Runs with slightly modified logic from the old `turnTo()` so there should be no issues (unless I screwed something up).

2024-01-04 02:50 UTC, SizzinSeal requested changes

2024-01-04 02:50 UTC, SizzinSeal commented on include/lemlib/chassis/chassis.hpp
> +        void turnToHeading(float targetTheta, int timeout, bool radians = false, bool forwards = true,
there should not be an option for radians. It's highly unlikely a user will use radians, and it makes the function call more complex

2024-01-04 02:50 UTC, SizzinSeal commented on src/lemlib/chassis/chassis.cpp
> +
The output should be slewed unless its within 20 degrees of the target

2024-01-04 02:50 UTC, SizzinSeal commented on src/main.cpp
> +    chassis.turnToHeading(M_PI, 1500, true);
remember to remove this when you remove the radians option

2024-01-04 05:37 UTC, SizzinSeal approved these changes
LGTM, will merge upon testing

2024-01-17 19:49 UTC, SizzinSeal commented
Has this been tested yet?

2024-01-17 20:24 UTC, SizzinSeal requested changes

2024-01-17 20:24 UTC, SizzinSeal commented on .DS_Store
This should not be here. Remove it, and I'll also add it to the gitignore

2024-01-17 20:24 UTC, SizzinSeal commented on include/lemlib/api.hpp
> +
why the newlines in this file?

2024-01-29 15:46 UTC, Miniongolf commented
NOTE: hasn't been fully tested yet, @edwart2cAKE is testing it.

2024-02-01 17:14 UTC, Miniongolf commented
Update: passed testing by @edwart2cAKE
<img width="377" alt="image" src="https://github.com/LemLib/LemLib/assets/74994367/de284789-7b32-4b6c-819f-4f5140675385">

2024-02-01 19:26 UTC, Rocky14683 commented
LGTM

2024-02-01 19:26 UTC, merged