Gamepad
LemLib/LemLib pull request #131
Opened 2024-01-12 16:10 UTC by DancingRicardo

#### Summary

A controller wrapper around the PROS Controller that adds extra functionality, such as shift keys, toggles, controller map modes, and auto-running functions.

#### Motivation

Add extra functionality to both the controller and LemLib.

#### Test Plan

Unit tests, and running it on the bot

2024-01-12 16:14 UTC, UvuvDev commented
Also, this has been tested and it works.

2024-01-17 19:41 UTC, SizzinSeal commented
has this been tested again after merging?

2024-01-17 21:54 UTC, SizzinSeal requested changes

2024-01-17 21:54 UTC, SizzinSeal commented on include/lemlib/devices/gamepad.hpp
> +struct LEMButtonMapping {
Not necessary to preface names with `LEM`

2024-01-17 21:54 UTC, SizzinSeal commented on include/lemlib/devices/gamepad.hpp
> +#include "unordered_map"
```suggestion
```
you have it included below

2024-01-17 21:54 UTC, SizzinSeal commented on src/lemlib/movements/pursuit.cpp
why has this been renamed?

2024-01-17 21:54 UTC, SizzinSeal commented on src/lemlib/devices/gamepad.cpp
> +    // }
you probably want to remove this

2024-01-17 21:54 UTC, SizzinSeal commented on include/lemlib/devices/gamepad.hpp
> +    private:
```suggestion
```

2024-01-20 15:36 UTC, closed without merging