👷 switch the pros build ci to an external repository
LemLib/LemLib pull request #200
Opened 2024-05-09 14:47 UTC by BattleCh1cken

#### Summary

This pull request changes the pros build ci to depend on an external repository rather than being written out directly.

## Download the template for this pull request: 

> [!NOTE]  
> This is auto generated from [`Add Template to Pull Request`](https://github.com/LemLib/LemLib/actions/runs/9672028161)
- via manual download: [LemLib@0.6.0+853264.zip](https://nightly.link/LemLib/LemLib/actions/artifacts/1638404612.zip)
- via PROS Integrated Terminal: 
 ```
curl -o LemLib@0.6.0+853264.zip https://nightly.link/LemLib/LemLib/actions/artifacts/1638404612.zip;
pros c fetch LemLib@0.6.0+853264.zip;
pros c apply LemLib@0.6.0+853264;
rm LemLib@0.6.0+853264.zip;
```

2024-06-11 16:43 UTC, BattleCh1cken commented
@meisZWFLZ squash and merge please

2024-06-11 19:24 UTC, ABUCKY0 requested changes

2024-06-11 19:24 UTC, ABUCKY0 commented on .github/workflows/pros-build.yml
> -        run: perl -i -pe 's@(?<=[^/])(docs/assets/.*?)(?=[")])@${{github.server_url}}/${{github.repository}}/blob/master/$1?raw=true@g' template/include/lemlib/README.md
We probably need to add this step back as a  step. 

```yml
# Checkout Step Before
- name: Update README.md
- run: |
  echo "\n## [Github link](${{github.server_url}}/${{github.repository}})" >> README.md
  perl -i -pe 's@(?<=[^/])(docs/assets/.*?)(?=[")])@${{github.server_url}}/${{github.repository}}/blob/master/$1?raw=true@g' README.md

2024-06-11 19:41 UTC, ABUCKY0 commented on .github/workflows/pros-build.yml
> -        run: perl -i -pe 's@(?<=[^/])(docs/assets/.*?)(?=[")])@${{github.server_url}}/${{github.repository}}/blob/master/$1?raw=true@g' template/include/lemlib/README.md
The only part that needs to be added back is the part that edits the readme

2024-06-11 19:43 UTC, ABUCKY0 requested changes

2024-06-11 19:43 UTC, ABUCKY0 commented on .github/workflows/pros-build.yml
> +        uses: LemLib/pros-build@v2.0.1
This also needs 

```yml
with:
  copy_readme_and_license_to_include: true
  lib_folder_name: lemlib
 ```
 
 If you want to, you could leave this as false and do the copying in a seperate step, or you can leave it up to the action.

2024-06-11 23:00 UTC, ABUCKY0 commented
Oh it's gonna fail because there isn't a lemlib folder

2024-06-12 01:03 UTC, BattleCh1cken commented
My vote would be to put this on pause until there is more work done on LemLib 0.6, and then once there's something in the repo to actually test, then we can merge this.

2024-06-12 01:40 UTC, ABUCKY0 commented
We could close this and move the changes to the v0.6-chassis-refactor branch since that's what's being worked on anyways

2024-06-12 17:47 UTC, BattleCh1cken commented
I did what you suggested, however the workflow is still failing due to the `include` directory not being present at all in the built template, even though it exists in code and is mentioned by the `Makefile`.

I have no idea what to do to solve this, help would be appreciated.

2024-06-12 17:57 UTC, ABUCKY0 commented
It’s not because of the include folder, it’s because include/***lemlib*** doesn’t exist. You might need to push another commit to make it rerun

2024-06-12 18:37 UTC, BattleCh1cken commented
`include/lemlib` exists, but `template/include` and `template/include/lemlib` both don't get created by `pros make template`.

2024-06-12 20:46 UTC, ABUCKY0 commented
That's not gonna do anything. I think its an issue with the Makefile

2024-06-26 01:01 UTC, SizzinSeal commented
@BattleCh1cken this still being worked on?

2024-06-26 01:35 UTC, BattleCh1cken commented
This should be ready to merge now I think. The issue I was having before was resolved.

2024-06-26 15:53 UTC, SizzinSeal commented
LGTM

2024-06-26 15:53 UTC, merged