Add methods for opcontrol on the chassis
LemLib/LemLib pull request #50
Opened 2023-08-14 02:42 UTC by BattleCh1cken

#### Summary

This pull request adds methods to the chassis that allow the robot to controlled during opcontrol.

Currently three different move methods are planned:

- tank drive
- arcade drive
- curvature drive

All of these movement methods can be modified with a drive curve

#### Test Plan

Upload the code to a robot, and drive around.

#### Additional Notes

This PR is obviously incomplete, and requires some work. This is because I wanted to ask if I should add support for the following features that I've seen mentioned:
- deadzones
- negative inertia accumulator (mentioned [here](https://wiki.purduesigbots.com/software/competition-specific/curvature-cheesy-drive))
- active braking

2023-08-14 03:24 UTC, BattleCh1cken commented
As of now the PR is tested and could be used as is. If the other features are desired I can still add them.

2023-08-14 23:24 UTC, SizzinSeal requested changes

2023-08-14 23:24 UTC, liam-teale commented on include/lemlib/chassis/chassis.hpp
> +
extra whitespace. How dare you?

2023-08-14 23:24 UTC, liam-teale commented on include/lemlib/chassis/chassis.hpp
> +
:sob:

2023-08-14 23:24 UTC, liam-teale commented on src/lemlib/chassis/opcontrol.cpp
> +double calcDriveCurve(double input, double scale) {
Missing doxygen comment

2023-08-14 23:24 UTC, liam-teale commented on src/lemlib/chassis/opcontrol.cpp
> +void Chassis::tank(int left, int right, float curveGain) {
Missing doxygen comment

2023-08-14 23:24 UTC, liam-teale commented on src/lemlib/chassis/opcontrol.cpp
> +void Chassis::arcade(int forward, int turn, float curveGain) {
Missing doxygen comment

2023-08-14 23:24 UTC, liam-teale commented on src/lemlib/chassis/opcontrol.cpp
> +void Chassis::curvature(int forward, int curvature, float cureveGain) {
Missing doxygen comment

2023-08-15 01:09 UTC, SizzinSeal approved these changes

2023-08-20 23:30 UTC, merged