Custom Logging Format
LemLib/LemLib pull request #59
Opened 2023-09-01 22:09 UTC by BattleCh1cken

#### Summary

This pull request adds support for custom logging formats to LemLib.

#### Motivation

This pull request is being created to make it possible for users to make graphical debuggers for odometry and PID. The new format API allows the user to customize LemLib's logging output to whatever their needs are.

#### Test Plan

The code needs to be run on a bot and each of the new logging methods need to be tested, along with changing the format.

#### Additional Notes

This PR is completely untested, and is therefore likely to change. I'd also like to give the user control over the refresh rate of the logger, but I need to do more testing to figure out how that will work.

This pull request is also completely undocumented. I will get that done as soon as I finish testing.

2023-09-02 20:26 UTC, BattleCh1cken commented
This PR has been now tested and works. The only thing that I'm unsure about it the way that other parts of the program access the logger. Currently I have a globally defined object defined the the logging header, but I don't know if this is a good idea.

A viable alternative could be making the user define the logger, and then taking a pointer to it in the chassiss's constructor. Note that this would also require taking it as input in the FAPID constructor as well.

2023-09-05 23:40 UTC, SizzinSeal requested changes

2023-09-05 23:40 UTC, SizzinSeal commented on src/lemlib/logger.cpp
This file needs some more comments in the source. E.x why are you using a deque? What does the buffer do?

2023-09-05 23:40 UTC, SizzinSeal commented on src/lemlib/pid.cpp
> +    if (log) { Logger::logPid(name, output, kI * error, kD * totalError, kD * deltaError); }
This line computes the outputs incorrectly
```suggestion
    if (log) { Logger::logPid(name, output, kP * error, kI * totalError, kD * deltaError); }
```

2023-09-05 23:40 UTC, SizzinSeal commented on include/lemlib/logger.hpp
> +        static void logPid(std::string name, float output, float p, float i, float d);
Error should be logged as well

2023-09-05 23:40 UTC, SizzinSeal commented on include/lemlib/logger.hpp
> +        static void startTask();
should be renamed
```suggestion
        static void initialize();
```

2023-09-05 23:40 UTC, SizzinSeal commented on src/main.cpp
> +#include "lemlib/logger.hpp"
Unnecessary include, logger.hpp is already included in api.hpp

2023-09-06 00:38 UTC, SizzinSeal approved these changes

2023-09-06 00:38 UTC, merged