add logger
LemLib/LemLib pull request #7
Opened 2023-02-13 05:58 UTC by Exortions

Custom logger for LemLib.

Untested: Colors may or may not work
Todo: Log things in actual LemLib implementations

Due to git issues, it is re-committing the doxygen pr.

2023-02-13 17:24 UTC, SizzinSeal commented
This should be implemented in existing functions (for example, throwing an error when trying to move the chassis before it has been calibrated). I'll take a closer look this afternoon and do some testing

2023-02-13 21:10 UTC, Exortions commented
yeah that was part of the todo, the logger itself is implemented but it needs to be called in functions.

will work on this later

2023-02-14 00:27 UTC, SizzinSeal commented on src/lemlib/logger.cpp
> +std::string getFormattedLevel(lemlib::logger::Level level) {
Missing break statements after each case

2023-02-14 00:29 UTC, SizzinSeal requested changes

2023-02-14 00:29 UTC, SizzinSeal commented on src/lemlib/logger.cpp
> +std::string getFormattedLevel(lemlib::logger::Level level) {
Missing break statements after each case

2023-02-14 00:29 UTC, SizzinSeal commented on src/lemlib/logger.cpp
> +    std::string messageString = "[LemLib] " + getFormattedLevel(level) +  ": " + message + ": " + exception;
missing reset ansi

2023-02-14 00:29 UTC, SizzinSeal commented on src/lemlib/logger.cpp
> +    std::string messageString = "[LemLib] " + getFormattedLevel(level) +  ": " + message;
missing reset ansi

2023-02-14 01:20 UTC, merged