Add telemetry as its own level
LemLib/LemLib pull request #88
Opened 2023-11-13 14:28 UTC by AbeetoChanito

#### Summary
Add telemetry as its own level.

#### Motivation
Telemetry data needs to have its own level because telemetry data can't really have a severity. It's literally just data.

2023-11-13 14:35 UTC, SizzinSeal commented on include/lemlib/logger/message.hpp
> +enum class Level { INFO, DEBUG, WARN, ERROR, FATAL, TELEMETRY };
Shouldn't telemetry be before info?

2023-11-13 14:36 UTC, SizzinSeal commented on include/lemlib/logger/buffer.hpp
> +        template <typename... T> void pushToBuffer(fmt::format_string<T...> format, T&&... args) {
where's the doxygen comment block?

2023-11-13 14:36 UTC, liam-teale commented on include/lemlib/logger/telemetrySink.hpp
> +         */
Document what the parameters do here

2023-11-13 14:37 UTC, SizzinSeal commented on include/lemlib/logger/telemetrySink.hpp
> +
whats up with this breakline? Its a 2-line function

2023-11-13 14:37 UTC, SizzinSeal commented on src/lemlib/logger/baseSink.cpp
> +bool BaseSink::isCombinedSink() { return !sinks.empty(); }
missing doxygen comment block

2023-11-13 14:41 UTC, SizzinSeal commented on src/lemlib/logger/buffer.cpp
>  void Buffer::setRate(uint32_t rate) { this->rate = rate; }
no doxygen comment block

2023-11-13 14:41 UTC, liam-teale commented on src/lemlib/logger/buffer.cpp
>  void Buffer::taskLoop() {
no doxygen comment block

2023-11-13 14:42 UTC, SizzinSeal commented on include/lemlib/logger/stdout.hpp
>           */
No parameters?

⠀⣞⢽⢪⢣⢣⢣⢫⡺⡵⣝⡮⣗⢷⢽⢽⢽⣮⡷⡽⣜⣜⢮⢺⣜⢷⢽⢝⡽⣝
⠸⡸⠜⠕⠕⠁⢁⢇⢏⢽⢺⣪⡳⡝⣎⣏⢯⢞⡿⣟⣷⣳⢯⡷⣽⢽⢯⣳⣫⠇
⠀⠀⢀⢀⢄⢬⢪⡪⡎⣆⡈⠚⠜⠕⠇⠗⠝⢕⢯⢫⣞⣯⣿⣻⡽⣏⢗⣗⠏⠀
⠀⠪⡪⡪⣪⢪⢺⢸⢢⢓⢆⢤⢀⠀⠀⠀⠀⠈⢊⢞⡾⣿⡯⣏⢮⠷⠁⠀⠀
⠀⠀⠀⠈⠊⠆⡃⠕⢕⢇⢇⢇⢇⢇⢏⢎⢎⢆⢄⠀⢑⣽⣿⢝⠲⠉⠀⠀⠀⠀
⠀⠀⠀⠀⠀⡿⠂⠠⠀⡇⢇⠕⢈⣀⠀⠁⠡⠣⡣⡫⣂⣿⠯⢪⠰⠂⠀⠀⠀⠀
⠀⠀⠀⠀⡦⡙⡂⢀⢤⢣⠣⡈⣾⡃⠠⠄⠀⡄⢱⣌⣶⢏⢊⠂⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⢝⡲⣜⡮⡏⢎⢌⢂⠙⠢⠐⢀⢘⢵⣽⣿⡿⠁⠁⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠨⣺⡺⡕⡕⡱⡑⡆⡕⡅⡕⡜⡼⢽⡻⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⣼⣳⣫⣾⣵⣗⡵⡱⡡⢣⢑⢕⢜⢕⡝⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⣴⣿⣾⣿⣿⣿⡿⡽⡑⢌⠪⡢⡣⣣⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⡟⡾⣿⢿⢿⢵⣽⣾⣼⣘⢸⢸⣞⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠁⠇⠡⠩⡫⢿⣝⡻⡮⣒⢽⠋⠀⠀⠀

2023-11-13 14:42 UTC, SizzinSeal requested changes
Sound idea. definitely needed. Clean it up, test, and i'll merge it in

2023-11-13 15:09 UTC, AbeetoChanito commented on include/lemlib/logger/telemetrySink.hpp
> +         */
I documented everything now, so this shouldn't be an issue for most of the logging codebase anymore.

2023-11-27 00:36 UTC, SizzinSeal approved these changes
LGTM. Will merge upon testing

2024-01-19 01:19 UTC, SizzinSeal commented
@AbeetoChanito you are aware this does not compile right

2024-04-20 23:35 UTC, AbeetoChanito commented
This has been open for far too long without any resolution. Also, I'm going to write LemLog anyway so this PR is not necessary for the release of 0.5.0. I'm going to close this PR.

2024-04-20 23:36 UTC, closed without merging