Add Poll Rate Option to Sensors
LemLib/LemLib pull request #94
Opened 2023-11-20 02:21 UTC by meisZWFLZ

#### Summary

This allows custom Encoders and Gyros to be created that have different poll rates than v5's.

#### Motivation

This is useful for unit testing, where time won't matter, and for other robotics applications outside of vex, like FRC.
#### Test Plan

- [ ] Test on a bot
#### Additional Notes

2023-11-22 17:14 UTC, liam-teale commented on src/lemlib/odom/differentialArc.cpp
> +    for (auto sensor : this->drivetrain) maxPollRate = std::max(maxPollRate, sensor.getPollRate());
```suggestion
    for (auto& sensor : this->horizontals) maxPollRate = std::max(maxPollRate, sensor.getPollRate());
    for (auto& sensor : this->verticals) maxPollRate = std::max(maxPollRate, sensor.getPollRate());
    for (auto& sensor : this->gyros) maxPollRate = std::max(maxPollRate, sensor->getPollRate());
    for (auto& sensor : this->drivetrain) maxPollRate = std::max(maxPollRate, sensor.getPollRate());
```
I may be wrong here, but shouldn't we copy by reference here?

2023-11-22 17:14 UTC, SizzinSeal commented on build/googletest-src
i don't think this is supposed to be here

2023-11-22 17:15 UTC, SizzinSeal requested changes
Pretty good overall. Make the changes and I'll merge upon testing

2023-11-22 17:53 UTC, meisZWFLZ commented on src/lemlib/odom/differentialArc.cpp
> +    for (auto sensor : this->drivetrain) maxPollRate = std::max(maxPollRate, sensor.getPollRate());
Don't know, but it doesn't throw me a compile error

2023-11-24 16:45 UTC, SizzinSeal approved these changes
LGTM. Will merge upon testing

2023-11-27 02:03 UTC, SizzinSeal commented
Bump, merge conflicts need resolution

2024-03-20 21:48 UTC, SizzinSeal commented
closing as refactor has been closed

2024-03-20 21:48 UTC, closed without merging