Add an abstract Path class for both static asset and SD card pure pursuit
LemLib/LemLib pull request #96
Opened 2023-11-20 17:31 UTC by Exortions

#### Summary
Add an abstract Path class for both static asset and SD card pure pursuit.
There is now a `Path` class that can be directly passed to `chassis.follow`.
The class has two implementations: `AssetPath` and `FilePath`. This allows pure pursuit to read from both static asset and the SD card.

#### Motivation
It was discussed in the server, as being able to have the flexibility of either SD card or static asset is useful.

#### Test Plan
This still needs to be tested, I don't have access to a chassis to test this with.

2023-11-22 17:21 UTC, SizzinSeal requested changes
Move semantics need changes

2023-11-22 17:21 UTC, SizzinSeal commented on include/lemlib/movements/purepursuit.hpp
> +        PurePursuit(float trackWidth, Path path, float lookaheadDist, int timeout, bool reversed, int maxSpeed);
```suggestion
        PurePursuit(float trackWidth, Path& path, float lookaheadDist, int timeout, bool reversed, int maxSpeed);
```
Copy the path by reference

2023-11-27 02:03 UTC, SizzinSeal commented
I'm not sure about the method by which this PR implements the functionality. While I do agree that the feature that this PR implements is required, I think that simply passing a vector of waypoints to pure pursuit will be better, and having functions which return a vector of waypoints given the asset name or file path.

2023-11-29 20:43 UTC, Exortions commented
I'll get it done tonight

2024-01-19 01:18 UTC, SizzinSeal commented
is this still active?

2024-02-24 19:33 UTC, closed without merging