✅ Add a unit testing system
LemLib/LemLib pull request #99
Opened 2023-11-20 20:44 UTC by BattleCh1cken

#### Summary

This pull request adds the ability to unit test parts of LemLib with the Googletest testing framework.

#### Motivation

This will help unsure the correctness of LemLib code without having to actually run it on a robot. This will not only speed up development, it will also directly deliver dopamine to my brain when I see all the tests pass.

#### Test Plan

Run the tests.

#### Additional Notes

Thanks to @meisZWFLZ for getting started on this.

The workflow will upload coverage data to [codecov.io](https://about.codecov.io/). An access token will have to be added to the repository so the data can be properly uploaded.

I pinky promise not to create another one of these. This is the last time I swear.

2023-11-23 03:13 UTC, SizzinSeal requested changes
Pay special attention to the license of raidzerolib

2023-11-23 03:13 UTC, SizzinSeal commented on .github/CONTRIBUTING.md
> +<!--TODO: write file structure guidelines-->
did you write the file structure guidelines?

2023-11-23 03:13 UTC, SizzinSeal commented on CMakeLists.txt
> +# Copied mostly from Ryan4253/RaidZeroLib: https://github.com/Ryan4253/RaidZeroLib/blob/06cc9796c5e7a1d8651d2b725cfde4c0e34d329f/CMakeLists.txt
is this compliant with the license of RaidZeroLib?

2023-11-23 14:02 UTC, BattleCh1cken commented
IP infringement should now be resolved.

2023-11-24 16:38 UTC, SizzinSeal approved these changes
LGTM

2023-11-24 16:44 UTC, merged